version: "3.9"

services:
  gateway:
    image: nginx:1.25-alpine
    container_name: ip_gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - ip_gateway.version=1.0
    networks:
      - ip_network
    depends_on:
      - auth-service
      - core-service

  # Servicio de Autenticacion
  auth-service:
    image: nginx:alpine
    container_name: auth_service
    volumes:
      - ./auth-service.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ip_network

  # Servicio de Core
  core-service:
    image: nginx:alpine
    container_name: core_service
    volumes:
      - ./core-service.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ip_network

networks:
  ip_network:
    driver: bridge
