# cpu cores, and expected traffic
worker_processes auto;

events {
    worker_connections 1024; # maximum number of simultaneous connections per worker process
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # limit_req_zone "test" zone=health_limit:2m rate=1r/s;
    # limit_req_zone $binary_remote_addr zone=api_limit:10m rate=3r/s;

    # Requerimiento 4: Limitar a 10 peticiones por segundo por IP.
    # 1mb: 16,000 direcciones IP
    # puede manejar hasta 160,000 clientes concurrentes
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    # Mapas de validacion: para validar si el api-key/api-origin estan vacios
    map $http_x_api_key $missing_api_key {
        "" 1;
        "~^\s*$" 1;
        default 0;
    }

    map $http_x_origin $missing_origin {
        "" 1;
        "~^\s*$" 1;
        default 0;
    }

    server {
        listen              80;
        server_name         localhost;
        limit_req           zone=api_limit burst=5 nodelay;
        limit_req_status    429;

        # /check - health check endpoint
        location /check {
            add_header Content-Type text/plain;

            return 200 'Gateway OK\n';
        }

        # Requerimiento 1 y 2: Enrutamiento a Auth
        location /api/v1/auth/ {
            # Si no hay llave, bloqueamos con 401
            if ($missing_api_key) { return 401 "x-api-key is required\n"; }

            # REQUERIMIENTO 3: Inyección del header x-origin hacia el servicio interno
            proxy_set_header x-origin "cian-gateway";

            # Comunicación con el servicio de autenticación (contenedor interno)
            proxy_pass http://auth-service:80/;
        }

        # REQUERIMIENTO 1 y 2: Enrutamiento a Core
        location /core/api/v1/ {
            # Validacion
            if ($missing_api_key) { return 401 "x-api-key is required\n"; }

            # REQUERIMIENTO 3: Inyección del header
            proxy_set_header x-origin "cian-gateway";

            # Comunicación con el servicio core (contenedor interno)
            proxy_pass http://core-service:80/;
        }

        # # /core/api/v1
        # location /core/api/v1 {
        #     if ($missing_api_key) { return 401 "x-api-key is required"; }
        #     if ($missing_origin) { return 401 "x-origin is required"; }

        #     add_header Content-Type text/plain;
        #     return 200 'Core API v1 OK';
        # }

        # /user/api/v1
        # location /user/api/v1 {
        #     if ($missing_api_key) { return 401 "x-api-key is required"; }
        #     if ($missing_origin) { return 401 "x-origin is required"; }

        #     add_header Content-Type text/plain;
        #     return 200 'User API v1 OK';

        # }

        # /user/api/v2
        # location /user/api/v2 {
        #     if ($missing_api_key) { return 401 "x-api-key is required"; }
        #     if ($missing_origin) { return 401 "x-origin is required"; }

        #     add_header Content-Type text/plain;
        #     return 200 'User API v2 OK';
        # }

        # Fallback para rutas no definidas: 404 personalizado
        error_page 404 = @custom_404;

        location / {
            # Si la ruta no coincide con las anteriores, devolver 404 personalizado
            try_files $uri $uri/ =404;
        }

        location @custom_404 {
            add_header Content-Type application/json;
            return 404 '{"error": "Not Found"}\n';
        }
    }
}





